'use client';

import { FormEvent, useEffect, useState } from 'react';
import { brochureDisclaimer, legalProgramNotice, programNames, type ApplicantAnswers, type ApplicantPlan } from '@/lib/applicant-planning';

const copy = {
  en: { title: 'Digital-UNI™ Applicant Planning Assistant', intro: 'Answer one short question at a time. OpenAI helps tailor your proposed brochure. Do not enter identification numbers, payment details, passwords, medical records, or immigration documents.', next: 'Next', edit: 'Edit Answers', regenerate: 'Regenerate Plan', approve: 'Approve and Generate Brochure', cancel: 'Cancel', preview: 'Live plan preview', resumeLabel: 'Attach your résumé', resumeHelp: 'Required PDF or DOCX file, maximum 3 MB. It is sent privately with your personalized brochure to Digital-UNI enrollment and financial aid.', consent: 'I explicitly consent to Digital-UNI storing and emailing the information in this proposal and my résumé for application review. I have read the privacy and retention notice.', privacy: 'Data is minimized, access-restricted, and retained for up to 24 months for application review unless law requires longer. Request access or deletion at enroll@digital-uni.net.', unavailable: 'AI Planning Assistant Coming Soon' },
  fr: { title: 'Assistant de planification des candidats Digital-UNI™', intro: 'Répondez à une courte question à la fois. OpenAI aide à personnaliser votre proposition de brochure. Ne saisissez pas de pièce d’identité, données bancaires, mots de passe, dossiers médicaux ou documents d’immigration.', next: 'Suivant', edit: 'Modifier les réponses', regenerate: 'Régénérer le plan', approve: 'Approuver et créer la brochure', cancel: 'Annuler', preview: 'Aperçu du plan', resumeLabel: 'Joindre votre CV', resumeHelp: 'Fichier PDF ou DOCX obligatoire, 3 Mo maximum. Il est envoyé de façon privée avec votre brochure aux services des inscriptions et de l’aide financière.', consent: 'Je consens explicitement au stockage et à l’envoi par courriel de cette proposition et de mon CV pour leur examen. J’ai lu l’avis de confidentialité et de conservation.', privacy: 'Les données minimales sont protégées et conservées jusqu’à 24 mois, sauf obligation légale. Demandez l’accès ou la suppression à enroll@digital-uni.net.', unavailable: 'Assistant de planification IA bientôt disponible' },
  ar: { title: 'مساعد Digital-UNI™ لتخطيط المتقدمين', intro: 'أجب عن سؤال قصير واحد في كل مرة. يساعد OpenAI في تخصيص كتيبك المقترح. لا تدخل أرقام الهوية أو بيانات الدفع أو كلمات المرور أو السجلات الطبية أو وثائق الهجرة.', next: 'التالي', edit: 'تعديل الإجابات', regenerate: 'إعادة إنشاء الخطة', approve: 'الموافقة وإنشاء الكتيب', cancel: 'إلغاء', preview: 'معاينة الخطة', resumeLabel: 'أرفق سيرتك الذاتية', resumeHelp: 'ملف PDF أو DOCX مطلوب، بحد أقصى 3 ميغابايت. يُرسل بشكل خاص مع الكتيب إلى فريقي التسجيل والمساعدة المالية.', consent: 'أوافق صراحة على تخزين هذه المعلومات وسيرتي الذاتية وإرسالها بالبريد لمراجعة الطلب. قرأت إشعار الخصوصية والاحتفاظ.', privacy: 'تُحفظ البيانات الضرورية فقط مع تقييد الوصول لمدة تصل إلى 24 شهرًا ما لم يتطلب القانون غير ذلك. لطلب الوصول أو الحذف: enroll@digital-uni.net.', unavailable: 'مساعد التخطيط بالذكاء الاصطناعي قريبًا' }
};

const questions = {
  en: ['What is your name?', 'What is your email?', 'What do you want to learn?', 'What is your current education and professional experience?', 'What career or professional outcome do you want?', 'Which program area interests you?', 'How many weeks or months can you study?', 'How many hours per week are available?', 'What is your tuition budget?', 'Do you prefer full payment or installments?', 'Are you requesting financial-aid information?', 'Which language do you prefer: English, Arabic, or French?'],
  fr: ['Quel est votre nom ?', 'Quelle est votre adresse e-mail ?', 'Que souhaitez-vous apprendre ?', 'Quels sont votre formation et votre expérience professionnelle ?', 'Quel résultat professionnel souhaitez-vous ?', 'Quel domaine de programme vous intéresse ?', 'Pendant combien de semaines ou de mois pouvez-vous étudier ?', 'Combien d’heures par semaine sont disponibles ?', 'Quel est votre budget de scolarité ?', 'Préférez-vous le paiement intégral ou les versements ?', 'Demandez-vous des informations sur l’aide financière ?', 'Quelle langue préférez-vous : anglais, arabe ou français ?'],
  ar: ['ما اسمك؟', 'ما بريدك الإلكتروني؟', 'ماذا تريد أن تتعلم؟', 'ما تعليمك الحالي وخبرتك المهنية؟', 'ما النتيجة المهنية التي تريدها؟', 'ما مجال البرنامج الذي يهمك؟', 'كم أسبوعًا أو شهرًا يمكنك الدراسة؟', 'كم ساعة متاحة أسبوعيًا؟', 'ما ميزانية الرسوم الدراسية؟', 'هل تفضل الدفع الكامل أم الأقساط؟', 'هل تطلب معلومات عن المساعدة المالية؟', 'ما لغتك المفضلة: الإنجليزية أم العربية أم الفرنسية؟']
};

const fields: (keyof ApplicantAnswers)[] = ['name','email','learningGoals','currentExperience','careerOutcome','programInterest','studyDuration','weeklyHours','budget','installmentPreference','financialAid','preferredLanguage'];
const initial = { name: '', email: '', learningGoals: '', currentExperience: '', careerOutcome: '', programInterest: programNames[0], studyDuration: '', weeklyHours: '', budget: '', installmentPreference: 'Full payment', financialAid: false, preferredLanguage: 'English' } satisfies ApplicantAnswers;

export function ApplicantAssistant({ locale, enabled }: { locale: 'en' | 'ar' | 'fr'; enabled: boolean }) {
  const t = copy[locale]; const [answers, setAnswers] = useState<ApplicantAnswers>(initial); const [step, setStep] = useState(0);
  const [isEnabled, setIsEnabled] = useState(enabled);
  const [value, setValue] = useState(''); const [plan, setPlan] = useState<ApplicantPlan | null>(null); const [busy, setBusy] = useState(false);
  const [planToken, setPlanToken] = useState('');
  const [resume, setResume] = useState<File | null>(null);
  const [error, setError] = useState(''); const [consent, setConsent] = useState(false); const [result, setResult] = useState<{ reference: string; brochureUrl: string } | null>(null);
  function choiceValue() { if (step === 5) return answers.programInterest; if (step === 9) return answers.installmentPreference; if (step === 10) return answers.financialAid; if (step === 11) return answers.preferredLanguage; return value; }
  async function generate(nextAnswers = answers) { setBusy(true); setError(''); const response = await fetch('/api/applicant-plan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(nextAnswers) }); const data = await response.json(); setBusy(false); if (!response.ok) return setError(data.error); setPlan(data.plan); setPlanToken(data.planToken); }
  function next(event: FormEvent) { event.preventDefault(); const raw = choiceValue(); if ((typeof raw === 'string' && !raw.trim()) || (step === 1 && !/^\S+@\S+\.\S+$/.test(String(raw)))) return setError('Please provide a valid answer.'); const updated = { ...answers, [fields[step]!]: raw }; setAnswers(updated); setError(''); setValue(''); if (step === fields.length - 1) void generate(updated); else setStep(step + 1); }
  async function submit() { if (!consent || !plan || !planToken) return setError('Explicit consent and a valid plan are required.'); if (!resume) return setError('Please attach your résumé as a PDF or DOCX file.'); const formData = new FormData(); formData.set('answers', JSON.stringify(answers)); formData.set('plan', JSON.stringify(plan)); formData.set('planToken', planToken); formData.set('consent', String(consent)); formData.set('website', ''); formData.set('resume', resume); setBusy(true); setError(''); const response = await fetch('/api/applicant-submit', { method: 'POST', body: formData }); const data = await response.json(); setBusy(false); if (!response.ok) return setError(`${data.error}${data.reference ? ` Reference: ${data.reference}` : ''}`); setResult(data); }
  function cancel() { setAnswers(initial); setPlan(null); setPlanToken(''); setStep(0); setValue(''); setResume(null); setConsent(false); setResult(null); setError(''); }
  useEffect(() => { fetch('/api/applicant-status', { cache: 'no-store' }).then(response => response.json()).then(data => setIsEnabled(Boolean(data.enabled))).catch(() => setIsEnabled(false)); }, []);

  return <section className="mx-auto max-w-7xl px-4 pb-20" aria-labelledby="assistant-title">
    <div className="mb-7"><h2 id="assistant-title" className="text-3xl font-bold text-navy-900">{t.title}</h2><p className="mt-3 max-w-4xl text-sm leading-6 text-navy-600">{t.intro}</p></div>
    {!isEnabled ? <div className="rounded-2xl border border-amber-300 bg-amber-50 p-8 text-center"><strong className="text-xl">{t.unavailable}</strong><p className="mt-3">The standard enrollment form remains available above.</p></div> :
    <div className="grid min-w-0 gap-6 lg:grid-cols-2">
      <div className="min-w-0 rounded-2xl border border-navy-100 bg-white p-5 shadow-card md:p-7">
        {!plan && !result && <form onSubmit={next}><p className="text-xs font-bold uppercase tracking-widest text-highlight-electric">{step + 1} / {fields.length}</p><label className="mt-4 block text-lg font-bold" htmlFor="assistant-answer">{questions[locale][step]}</label>
          {step === 5 ? <select id="assistant-answer" value={answers.programInterest} onChange={e => setAnswers({ ...answers, programInterest: e.target.value as ApplicantAnswers['programInterest'] })} className="mt-4 min-h-12 w-full rounded-lg border p-3">{programNames.map(x => <option key={x}>{x}</option>)}</select> : step === 9 ? <select id="assistant-answer" value={answers.installmentPreference} onChange={e => setAnswers({ ...answers, installmentPreference: e.target.value as ApplicantAnswers['installmentPreference'] })} className="mt-4 min-h-12 w-full rounded-lg border p-3"><option>Full payment</option><option>Installments</option></select> : step === 10 ? <select id="assistant-answer" value={String(answers.financialAid)} onChange={e => setAnswers({ ...answers, financialAid: e.target.value === 'true' })} className="mt-4 min-h-12 w-full rounded-lg border p-3"><option value="false">No</option><option value="true">Yes</option></select> : step === 11 ? <select id="assistant-answer" value={answers.preferredLanguage} onChange={e => setAnswers({ ...answers, preferredLanguage: e.target.value as ApplicantAnswers['preferredLanguage'] })} className="mt-4 min-h-12 w-full rounded-lg border p-3"><option>English</option><option>Arabic</option><option>French</option></select> : <textarea id="assistant-answer" rows={step === 1 ? 1 : 3} value={value} onChange={e => setValue(e.target.value)} className="mt-4 w-full rounded-lg border p-3" maxLength={1500} />}
          <button className="mt-5 min-h-12 w-full rounded-lg bg-gold-500 px-6 font-bold" disabled={busy}>{busy ? '…' : t.next}</button></form>}
        {plan && !result && <div><h3 className="text-xl font-bold">Review before submission</h3><p className="mt-3 text-sm">Your request does not approve enrollment, aid, credit, certification, installments, or scholarships.</p><div className="mt-5 rounded-lg border border-navy-100 p-4"><label className="block text-sm font-bold" htmlFor="applicant-resume">{t.resumeLabel}</label><p id="applicant-resume-help" className="mt-2 text-xs leading-5 text-navy-600">{t.resumeHelp}</p><input id="applicant-resume" type="file" required accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" aria-describedby="applicant-resume-help" onChange={event => { const file = event.target.files?.[0] ?? null; if (file && file.size > 3 * 1024 * 1024) { event.target.value = ''; setResume(null); setError('The résumé must be 3 MB or smaller.'); return; } setResume(file); setError(''); }} className="mt-3 block w-full text-sm file:me-4 file:rounded-md file:border-0 file:bg-navy-900 file:px-4 file:py-3 file:font-bold file:text-white" />{resume && <p className="mt-2 break-all text-xs font-semibold text-emerald-700">Selected: {resume.name}</p>}</div><label className="mt-5 flex gap-3 rounded-lg bg-navy-50 p-4 text-sm"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} className="h-6 w-6 shrink-0" />{t.consent}</label><p className="mt-3 text-xs leading-5">{t.privacy}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><button onClick={() => { setPlan(null); setStep(0); }} className="min-h-12 rounded-lg border font-bold">{t.edit}</button><button onClick={() => void generate()} disabled={busy} className="min-h-12 rounded-lg border font-bold">{t.regenerate}</button><button onClick={() => void submit()} disabled={busy || !consent || !resume} className="min-h-14 rounded-lg bg-gold-500 px-3 font-bold disabled:opacity-50">{t.approve}</button><button onClick={cancel} className="min-h-14 rounded-lg bg-navy-100 font-bold">{t.cancel}</button></div></div>}
        {result && <div role="status" className="rounded-xl border border-green-300 bg-green-50 p-6"><h3 className="text-xl font-bold">Application submitted</h3><p className="mt-2">Reference: <strong>{result.reference}</strong></p><a className="mt-5 inline-flex min-h-12 items-center rounded-lg bg-navy-900 px-5 font-bold text-white" href={result.brochureUrl} target="_blank" rel="noreferrer">Secure brochure download</a></div>}
        {error && <p role="alert" className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}
      </div>
      <details open={Boolean(plan)} className="min-w-0 rounded-2xl border border-navy-100 bg-navy-50 p-5 lg:block md:p-7"><summary className="cursor-pointer text-xl font-bold lg:pointer-events-none">{t.preview}</summary>{plan ? <div className="mt-5 space-y-4 break-words text-sm"><h3 className="text-2xl font-bold">{plan.recommendedProgram}</h3><p><strong>Applicant:</strong> {plan.applicantName} ({plan.applicantEmail})</p><p><strong>Goals:</strong> {plan.learningGoals}</p><p><strong>Experience:</strong> {plan.currentExperience}</p><p><strong>Alternative:</strong> {plan.alternativeProgram}</p><p><strong>Duration:</strong> {plan.proposedDuration}</p><p><strong>Schedule:</strong> {plan.weeklySchedule.join(' · ')}</p><p><strong>Skills and modules:</strong> {plan.skillsAndModules.join(' · ')}</p><p><strong>Applied project:</strong> {plan.appliedProject}</p><p><strong>AI application outcome:</strong> {plan.personalizedAiApplicationOutcome}</p><p><strong>Tuition starts at:</strong> ${plan.tuitionStartingPrice.toLocaleString()} USD</p><p><strong>Stated budget:</strong> {plan.applicantBudget}</p><p><strong>Payment preference request:</strong> {plan.requestedInstallmentPreference}</p><p><strong>Financial-aid information:</strong> {plan.financialAidInquiryStatus ? 'Requested' : 'Not requested'}</p><ul className="list-disc ps-5">{plan.assumptionsAndDisclaimers.map(x => <li key={x}>{x}</li>)}</ul><p className="font-semibold">{legalProgramNotice}</p><p className="rounded-lg border border-amber-300 bg-amber-50 p-3">{brochureDisclaimer}</p></div> : <p className="mt-5 text-sm text-navy-500">Your validated proposal will appear here after the questions are complete.</p>}</details>
    </div>}
  </section>;
}
